# M1 - depósitos à vista - média
# Frequência: Mensal com início em 1980.01
# Fonte: Banco Central do Brasil, Notas Econômico-financeiras para a Imprensa, Política Monetária e Operações de Crédito do SFN (Bacen/Not. Imp./Moeda)
# Unidade: R$ (milhões) 
# Comentário: Quadro XXXVII - Meios de pagamento e componentes - Média dos saldos nos dias úteis. Obs.: Com base nos dias úteis. Engloba os depósitos à vista efetivamente movimentáveis por cheques, prontamente disponíveis para pagamento de bens e serviços e aceitos como moeda.
# Ref: Ferreira_Mattos_2016 - http://portalibre.fgv.br/lumis/portal/file/fileDownload.jsp?fileId=8A7C82C5519A547801533DF7BE5E2D0D
# manual X13 https://www.census.gov/ts/x13as/docX13ASHTML.pdf
# data and X-13ARINA-SEATS configuration
download.file("https://www.census.gov/ts/x13as/pc/x13as_V1.1_B39.zip", destfile = "./x13.zip")
unzip("x13.zip")
local <- paste0(getwd(), "/x13as")
Sys.setenv(X13_PATH = local)
library(seasonal) # https://cran.r-project.org/web/packages/seasonal/seasonal.pdf
library(dplyr)
library(tidyr)
library(htmltab)
library(lubridate)
library(zoo)

url <- "http://www.ipeadata.gov.br/ExibeSerie.aspx?serid=32302&module=M"
data <- htmltab(doc = url, which = "//table[@id='grd_DXMainTable']", rm_nodata_cols = TRUE)
names(data) <- c("month", "demandDeposits")
data$demandDeposits <- gsub("\\.", "", data$demandDeposits)
data$demandDeposits <- gsub(",", "\\.", data$demandDeposits)
data$demandDeposits <- as.numeric(data$demandDeposits)
data$demandDeposits <- round(data$demandDeposits, 0)
data$month <- ymd(data$month, truncated = 2)
data <- subset(data, data$month > as.Date("2000-12-01"))
data.ts <- ts(data[, 2], start = c(2001, 1), freq = 12)

# sasonalized data
plot(data.ts, main = "M1 - Demand deposit time series - Brazil")
abline(h = seq(40000, 180000, 10000), v = seq(2000, 2017, 1), lty = 3, col = "gray")

# sasonalized data by month
monthplot(data.ts, labels = month.abb, lty.base = 2, main ="M1 Demand deposits by month - Brazil")
legend("topleft", legend = c("Demand Deposit/Month", "Average/Month"), cex = 0.8, lty = c(1,2), bty = "n")

# trailing 12m - by month (Optional to compare against the curve generated by out seas model)
data$demandDeposits12m    <- rollsum(data$demandDeposits, k = 12, fill = NA, align = "right")
data$demandDeposits12m.ts <- ts(data$demandDeposits12m, start = c(2001, 1), freq = 12) / 12
plot(data$demandDeposits12m.ts, main = "M1 - Demand deposit time series - Brazil")
abline(h = seq(40000, 180000, 10000), v = seq(2000, 2017, 1), lty = 3, col = "gray")


ajusted.data <- seas(x = data.ts)
qs(ajusted.data)
summary(ajusted.data)

# spectrum series
spec_orig  <- series(ajusted.data, "sp0")
spec_sa    <- series(ajusted.data, "s1s")
spec_resid <- series(ajusted.data, "spr")
spec_irreg <- series(ajusted.data, "s2s")


# frequency
freq <- c((1:6)/12, 0.3482, 0.4326)
plot(spec_orig, type = "l", main = "Original series")
abline(  v = freq,
       col = c(rep("red", 6), "blue", "blue"),
       lty = c(rep(2, 6), 3, 3)
       )
legend("topleft", 
       legend = c("Orig", "S. Effects", "Td. Effects"),
       cex = 0.7, lty = 1:3, bty = "n", col = c(1, 2, 4)
       )


# slidingspans is not working
## sliding <- series(ajusted.data, "slidingspans.sfspans")
## sum(sliding[, "Max_._DIFF"] > 3, na.rm = TRUE) + length(na.omit(sliding[, "Max_._DIFF"])) * 100


# workday - Brazil
url2 <- "http://www.ipeadata.gov.br/ExibeSerie.aspx?serid=459044792&module=M"
workday <- htmltab(doc = url2, which = "//table[@id='grd_DXMainTable']", rm_nodata_cols = TRUE)
names(workday)   <- c("month", "workday")
workday$workday  <- as.numeric(workday$workday)
workday$month    <- ymd(workday$month, truncated = 2)
workday          <- workday %>%
                    filter(month > as.Date("2000-12-01")) %>%
                    mutate(nDays = days_in_month(month)) %>%
                    mutate(nonWorkday = nDays - workday) %>%
                    mutate(workdayOk = workday - (5/2)*nonWorkday)
workday          <- ts(workday[,5], start = c(2001, 1), end = c(2025, 12), freq = 12)

# moving holidays - Brazil
holiday         <- read.csv2("feriados_nacionais.csv", sep = ",", encoding = "UTF-8", colClasses = c(NA, "NULL", NA))
holiday$Data    <- mdy(holiday$Data)
holiday.edited  <- holiday %>%
                  mutate(year = year(Data))

dates.carnival  <- holiday.edited %>%
                  filter(Feriado == "Carnaval")
dates.carnival  <- as.Date(dates.carnival$Data)
carnival <- genhol(dates.carnival, start = -3, end = 1, frequency = 12)

dates.christmas <- holiday.edited %>%
                  filter(Feriado == "Natal")
dates.christmas <- as.Date(dates.christmas$Data)
christmas <- genhol(dates.christmas, start = -1, end = 1, frequency = 12)

# holiday and  workdays
regs <- na.omit(cbind(workday, carnival))
regs <- as.ts(window(regs, end = c(2025, 12)))

easter    <- genhol(x = easter)
cny       <- genhol(x = cny)
demonio   <- cny
teste     <- cbind(easter, demonio)

# deseasonalized data
ajusted.data.d <- seas(x = data.ts, xreg = regs, regression.aictest = NULL, regression.usertype = c("td"), transform.function = "None")
qs(ajusted.data.d)
summary(ajusted.data.d)

# spectrum series - deseasonalized
spec_orig.d  <- series(ajusted.data.d, "sp0")
spec_sa.d    <- series(ajusted.data.d, "s1s")
spec_resid.d <- series(ajusted.data.d, "spr")
spec_irreg.d <- series(ajusted.data.d, "s2s")

# ajusted frequency - deseasonalized
freq.d <- c((1:6)/12, 0.3482, 0.4326)
plot(spec_sa.d, type = "l", main = "Ajusted series")
abline(  v = freq.d,
         col = c(rep("red", 6), "blue", "blue"),
         lty = c(rep(2, 6), 3, 3)
)
legend("topleft", 
       legend = c("Orig", "S. Effects", "Td. Effects"),
       cex = 0.7, lty = 1:3, bty = "n", col = c(1, 2, 4)
)

monthplot(ajusted.data.d, col.base = 1)
legend("topleft", legend = c("Irregular", "Seasonal", "Seasonal Average"), 
        col = c(4, 2, 1), lwd = c(1, 2, 2), lty = 1, bty = "n", cex = 0.6)

plot(ajusted.data.d)
grid()
legend("topleft", legend = c("Original", "Ajusted"),
       col = c(1, 2), lwd = c(1, 2), lty = 1, bty = "n", cex = 0.6)

# full html report
out(ajusted.data.d)

# forecast
prev <- window(series(ajusted.data.d, "fct"), freq = 12)
ts.plot(data.ts, prev, col = c(1, 1, 4, 4), lwd = c(1, 2, 1, 1))
grid()
legend("topleft", legend = c("Demand Deposits Forecast", "CI 95%"),
       lty = 1, col = c(1, 1, 4), lwd = c(1, 2, 1, 1), bty = "n", cex = 0.7)

# ajusted forecast - deseasonalized
ajusted.data.d2 <- seas(x = data.ts, xreg = regs, regression.aictest = NULL, regression.usertype = c("td"), transform.function = "None", seats.appendfcst = "yes")
fcst <- window(series(ajusted.data.d2, "s11"), start = c(2017, 1), freq = 12)
fit <- window(series(ajusted.data.d2, "s11"), end = c(2016, 12), freq = 12)
ts.plot(data.ts, fit, fcst, col = c(1, 2, 4), lwd = c(1, 2, 2))
grid()
legend("topleft", legend = c("Demand Deposits", "Ajusted Demand Deposits", "Ajusted Demand Deposits Forecast"),
       lty = 1, col = c(1, 2, 4), lwd = c(1, 2, 2), bty = "n", cex = 0.7)

